export const ACTIONS = {
  CALL: 'call',
  GET_CHANNELS: 'get-channels',
  JOIN_CHANNEL: 'join-channel',
  LEAVE_CHANNEL: 'leave-channel',
  SHARE_CHANNELS: 'share-channels',
  CREATE_CHANNEL: 'create-channel',
  STOP_CALL: 'stop-call',
  ADD_PEER: 'add-peer',
  REMOVE_PEER: 'remove-peer',
  RELAY_SDP: 'relay-sdp',
  RELAY_ICE: 'relay-ice',
  ICE_CANDIDATE: 'ice-candidate',
  SESSION_DESCRIPTION: 'session-description',
  ASK_PERMISSION: 'ask-permission',
  CALL_PERMISSION: 'call-permission',
  RELAY_PERMISSION: 'relay-permission',
  HIDE_CAM: 'hide-cam',
  HANDLE_CAM: 'handle-cam'
}